package si.fri.rso.comments.services;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.stereotype.Controller;
import org.springframework.stereotype.Service;
import si.fri.rso.comments.models.entities.Comment;
import si.fri.rso.comments.models.repositories.CommentRepository;

@Component
public class CommentService {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private CommentRepository commentRepository;


    public Comment addComment(Comment s){
        return commentRepository.save(s);
    }

    public Iterable<Comment> getAllComments(){
        return commentRepository.findAll();
    }

    public Iterable<Comment> getAllCommentsForStation(Integer id) { return commentRepository.findAllByStationID(id); }
}
