package si.fri.rso.comments.services;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.scheduling.annotation.Async;
import org.springframework.stereotype.Component;
import si.fri.rso.comments.models.entities.Comment;
import si.fri.rso.comments.models.repositories.CommentRepository;

import java.util.concurrent.CompletableFuture;

@Component
public class CommentService {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private CommentRepository commentRepository;


    public Comment addComment(Comment s){
        return commentRepository.save(s);
    }

    @Async
    public CompletableFuture<Iterable<Comment>> getAllComments(){
        Iterable<Comment> c = commentRepository.findAll();
        return CompletableFuture.completedFuture(c);
    }

    @Async
    public CompletableFuture<Iterable<Comment>> getAllCommentsForStation(Integer id) {
        Iterable<Comment> c = commentRepository.findAllByStationID(id);
        return CompletableFuture.completedFuture(c);
    }
}
